### ISSUE TITLE
Change git pre-commit hook to pre-push

### ISSUE THREAD

**Issue by konekoya** [twreporter/twreporter-react#1039]
Hello there 👋

I was trying to improve the README.md today. And have noticed that this project has a pre-commit hook setup. While this is generally a good practice to run linting and testing before adding any new commits. This also slows down the pace of working on this project. The linting part is not that bad/slow but the testing part took me about 4 minutes to finish.

I think it would be great if we can change the git hook from pre-commit to pre-push. That way, we can still check these things before pushing onto GitHub, but also, make the overall dev experience a bit better and faster since we're not blocking them when creating new commits. 

 just my two cents :)
Joshua

**Comment by nickhsine** [comment]
Sorry for late reply.
The slow part should be UI testing.
We run three `pre-commit`s, including, linting, unit test and UI test.
Currently the UI test takes lots of time, we will try to figure out how to improve this drawback.

We will move UI test from `pre-commit` to `pre-push` in the next PR.
Before the PR is done, if you want to skip UI test, you can add `git commit --no-verify` to speed up the development.

thanks for your advice.

**Comment by nickhsine** [comment]
@konekoya 
The PR is merged.
If you have any problems, please reopen the issue.

**Comment by nickhsine** [comment]
By the way, if you haven't change any UI components,
you can skip `ui-test` by append `--no-verify` behind the git command when git pushing.

**Comment by konekoya** [comment]
@nickhsine Thanks much for this! Going to try this out as soon as I can :)
