### ISSUE TITLE
Header 2.0 implementation.

### ISSUE THREAD

**Issue by nickhsine** [twreporter/twreporter-react#1101]
After header 2.0 mockup releases,
there are several pages need to change.

- [ ] topic page, such as (https://www.twreporter.org/topics/national-pension)
- [ ] index page (https://www.twreporter.org/) 
- [x] particular article page (https://www.twreporter.org/a/high-risk-youth-left-in-relic)

**Comment by taylrj** [comment]
close due to new header design is in progress.
