### ISSUE TITLE
Use travis-ci for code quality

### ISSUE THREAD

**Issue by jessy1092** [twreporter/twreporter-react#112]
[Travis-ci](https://travis-ci.org/) can check every commit and PR to make sure code quality.(Run lint and test)

It is free for open source project.

**Comment by yutin1987** [comment]
:100:

**Comment by yutin1987** [comment]
maybe, we can try [codecov.io](https://codecov.io/), it have coverage report in PR.
![screen shot 2015-12-28 at 10 43 34 am](https://cloud.githubusercontent.com/assets/2505934/12013361/e8881a72-ad4f-11e5-97ea-9f8676a80080.png)

**Comment by stegben** [comment]
I suggest use `nyc` package for code coverage which we can generate the report locally

**Comment by nickhsine** [comment]
Sorry for the late reply.
We are currently writing unit tests and building up Jenkins server for testing.
Once the unit tests are done, we can run the tests and lint locally.

**Comment by nickhsine** [comment]
Latest information about CI/CD, we already integrated with circleci.
