### ISSUE TITLE
Add full-text search to homepage

### ISSUE THREAD

**Issue by audreyt** [twreporter/twreporter-react#118]
Google CSE is an easy (maybe a bit expensive) choice. Or maybe in-browser search based on a simple `.indexOf` ? 

Source: https://www.facebook.com/portnoyzheng/posts/10153190268136555?comment_id=10153190304146555&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by hcchien** [comment]
We might be able to add the CSE first.

**Comment by audreyt** [comment]
Closed now that CSE is deployed.
