### ISSUE TITLE
Google SEO

### ISSUE THREAD

**Issue by yutin1987** [twreporter/twreporter-react#120]
![screen shot 2015-12-28 at 11 07 05 am](https://cloud.githubusercontent.com/assets/2505934/12013524/33c694ca-ad53-11e5-9067-c666e02918ad.png)
- [x] that title should is "報導者The Reporter"
- [x] description

ref.
1. https://support.google.com/webmasters/answer/79812
2. http://seositecheckup.com/seo-audit/www.twreporter.org

**Comment by yutin1987** [comment]
![screen shot 2015-12-28 at 11 29 25 am](https://cloud.githubusercontent.com/assets/2505934/12013639/5e9812b6-ad56-11e5-89a0-73dba4c65260.png)
![screen shot 2015-12-28 at 11 29 51 am](https://cloud.githubusercontent.com/assets/2505934/12013641/60915f0a-ad56-11e5-80fc-350c4d37b5bf.png)

**Comment by nickhsine** [comment]
Sure, will add this later.
However, if you want to give us a patch.
We will love it:)

**Comment by nickhsine** [comment]
close it because of https://github.com/twreporter/twreporter-react/pull/124
