### ISSUE TITLE
react CSS Modules

### ISSUE THREAD

**Issue by yutin1987** [twreporter/twreporter-react#126]
`css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader`
or
`css-loader?modules&importLoaders=1&localIdentName=[name]__[local]!postcss-loader`

webpack
```
module: {
  loaders: [
    {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract('style-loader',
      'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]!postcss-loader')
    }
  ]
}
```

ref.
1. https://github.com/gajus/react-css-modules
2. https://github.com/webpack/css-loader
3. https://css-modules.github.io/webpack-demo/

**Comment by kidwm** [comment]
You should change issue title to CSS Modules

**Comment by yutin1987** [comment]
this is a nice file structure, have .js .css & __test__
https://github.com/react-toolbox/react-toolbox/tree/dev/components/button
a discussion

**Comment by yutin1987** [comment]
@kidwm Thanks, Done :+1:

**Comment by nickhsine** [comment]
This one is cool,
we will update this after Search implemented.
However, if you want to give us a patch, please feel free.

**Comment by yutin1987** [comment]
ok, maybe I can do it at weekend.

**Comment by nickhsine** [comment]
;) thank you in advance

**Comment by nickhsine** [comment]
@yutin1987 
Because we have server side rendering, hence should we use https://github.com/halt-hammerzeit/webpack-isomorphic-tools?

**Comment by yutin1987** [comment]
@nickhsine yes, we need it.

**Comment by nickhsine** [comment]
@yutin1987 
cool, I will be starting this modification soon.

**Comment by nickhsine** [comment]
@yutin1987 we have CSS module now. 
We can start to write ``` const styles = require('./xxx.scss'); ``` for new features.
Nick

**Comment by yutin1987** [comment]
nice :100:
