### ISSUE TITLE
Duplicate text on website

### ISSUE THREAD

**Issue by typebrook** [twreporter/twreporter-react#1345]
![Screenshot from 2019-09-04 10-30-45](https://user-images.githubusercontent.com/19887090/64222009-576a1e00-cf01-11e9-95e9-6df8ec19cade.png)

**Comment by nickhsine** [comment]
@taylrj 
可以幫忙修正一下這個問題嗎？

**Comment by taylrj** [comment]
ok !

**Comment by taylrj** [comment]
問題已修正，感謝回報 👍！
