### ISSUE TITLE
hamburger menu bar in mobile device 

### ISSUE THREAD

**Issue by hcchien** [twreporter/twreporter-react#138]
add the hamburger menu bar in mobile device

**Comment by hcchien** [comment]
![- -](https://cloud.githubusercontent.com/assets/101658/12091284/e27f7efe-b330-11e5-9d09-ef96fb690cb2.jpg)

**Comment by hcchien** [comment]
![-](https://cloud.githubusercontent.com/assets/101658/12091562/d1e29124-b332-11e5-9084-0731e0a45a2d.jpg)

**Comment by garfieldduck** [comment]
This PR is related to the mobile menu issue: https://github.com/twreporter/twreporter-react/pull/146

**Comment by garfieldduck** [comment]
This issue has been resolved.

**Comment by garfieldduck** [comment]
This issue has been resolved.
