### ISSUE TITLE
Top-level navigation does not work in Firefox

### ISSUE THREAD

**Issue by audreyt** [twreporter/twreporter-react#141]
On homepage, clicking any of the top-level categories results in:

```
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
x.setValueForStyles()
 main.js:76
r.measure/a()
 main.js:1
b.Mixin._updateDOMProperties()
 main.js:78
```

Chrome and Safari works just fine.

**Comment by nickhsine** [comment]
@audreyt @hcchien 
This problem seems to be caused by ```react-burger-menu```.
Will remove burger menu first to make firefox work.

**Comment by nickhsine** [comment]
https://github.com/twreporter/twreporter-react/pull/144 temporarily fixed by removing ```react-burger-menu```

**Comment by stanleycyang** [comment]
Why is react-burger-menu an issue? I don't follow the train of logic
