### ISSUE TITLE
Footer style is inconsistent

### ISSUE THREAD

**Issue by sorarize** [twreporter/twreporter-react#150]
首頁
![image](https://cloud.githubusercontent.com/assets/240043/12773581/fb7d4306-ca77-11e5-83f5-293176be22d9.png)

[專欄](https://www.twreporter.org/a/opinion-japan-report-twelection)
![image](https://cloud.githubusercontent.com/assets/240043/12773585/0b9b714a-ca78-11e5-833d-c77316bcef2a.png)

[infographic](https://www.twreporter.org/a/infographics-2016-election)
![image](https://cloud.githubusercontent.com/assets/240043/12773657/a26bef0a-ca78-11e5-9002-407161030084.png)

**Comment by kidwm** [comment]
BTW, how about move `twreporter-react-footer-components` and other components to npm orgs?

https://www.npmjs.com/docs/orgs/

**Comment by nickhsine** [comment]
The footer is consistent now.

**Comment by nickhsine** [comment]
@kidwm thanks for your suggestion, we will try it.
