### ISSUE TITLE
Production: TypeError: "e[n] is undefined" (2019/12/30 22:45)

### ISSUE THREAD

**Issue by flameddd** [twreporter/twreporter-react#1537]
## Problem
- website broke when visit https://www.twreporter.org/a/online-gambling-industry-taiwan-role

## Screen shot  
![圖片](https://user-images.githubusercontent.com/22259196/71586130-118e3100-2b54-11ea-9093-a13f6804942d.png)

## Environment
- OS: win7
- Browser: **Firefox** 71.0 (64bit), both **normal** and **private** tab
  - **chrome** is fine

# A real purpose about this issue
I just want to say **GOOD JOB** to the dev Team. Bcuz twreporter is
- well performance
- good design
- PWA installable (I never saw any News/CMS website with PWA installable)

feel **FREE** to close this issue **WITHOUT** reason！

👍 👍 👍 👍 👍

**Comment by flameddd** [comment]
`Redux DevTools` extension may cuz this issue.

**Comment by flameddd** [comment]
**Issue solved** after I upgrade my `Redux DevTools (Firefox add-on)`.  
So I close this issue, **sorry for bothering**

**Comment by flameddd** [comment]
ref:
- https://stackoverflow.com/questions/53321090/redux-typeerror-en-is-undefined-when-configuring-redux-store-in-reactjs-app

**Comment by nickhsine** [comment]
Thanks for your feedback.
Glad your problem solved.
Please feel free to open issues if needed.
