### ISSUE TITLE
Desktop sidebar overlaps on the footer

### ISSUE THREAD

**Issue by achinchen** [twreporter/twreporter-react#1846]
## Bug report
Browsing website and found sidebar layout issue.

### Description 
Found desktop sidebar overlaps on the footer.

### Steps to reproduce
Using screen width wider than 768px, and scroll page to bottom.

### Actual behavior
Sidebar overlays on the footer.

### Expected behavior
Sidebar doesn't overlay on the footer.

### Screenshots
![Untitled](https://user-images.githubusercontent.com/40432044/117092112-ee9b0f00-ad8f-11eb-87da-2f856f228110.png)

### Possible solution
Update sidebar style.
If the behavior I referred above is accepted, I'm happy to make PR to update it.

**Comment by taylrj** [comment]
Thanks for the report.

The expected behavior referred above is acceptable.
Feel free to make a pull request or comments below.

Thank you~

**Comment by achinchen** [comment]
@taylrj I opened the PR to fix it issue, please review it.
