### ISSUE TITLE
Article revamp requirements for Desktop

### ISSUE THREAD

**Issue by nickhsine** [twreporter/twreporter-react#189]
### Features (DESKTOP)(PENDING, wait for spec)
- [x] BlockAlignmentWrapper
- [x] Title
- [x] HeadingAuthor 
- [x] BottomAuthor (spec ready)
- [x] Image
- [x] ImageDiff (spec ready)
- [ ] Slideshow (spec ready)
- [ ] Introduction (include 前言, spec change）
- [x] LeadingImage
- [ ] Body
- [x] Paragraph 
- [ ] Embedded (spec ready)
- [x] Audio (spec ready)
- [ ] Annotation (註解, spec ready)
- [ ] Quote (spec ready)
- [x] InfoBox (spec change)
- [x] Bottom Tags (spec  #ready)
- [ ] Bottom Related Stories
- [ ] Footer
- [x] Image Lazy Load
- [x] Aside Related Stories
- [x] Reading Progress Bar
- [ ] Set paragraph anchor to the url
### Features (Mobile)
- [x] Title
- [x] HeadingAuthor 
- [x] ~~BottomAuthor (spec change, removed)~~
- [x] Image
- [x] ImageDiff (spec ready)
- [x] Slideshow (spec ready)
- [x] Introduction (include 前言）
- [x] LeadingImage
- [x] Body
- [x] Paragraph 
- [x] Embedded video (spec ready)
- [ ] Embedded graphics (spec not ready) 
- [x] Audio (spec ready)
- [ ] Audio without coverphoto (spec not ready)
- [ ] Annotation (註解, spec not ready)
- [x] InfoBox (spec ready)
- [ ] Bottom Tags (spec  #ready)
- [ ] Bottom Related Stories
- [ ] Footer
- [x] Image Lazy Load
- [x] Reading Progress Bar
- [ ] Set paragraph anchor to the url
### Performance Tuning
- [ ] remove properties we don't need in the api repsonse
- [ ] add browser cache

**Comment by nickhsine** [comment]
https://github.com/twreporter/twreporter-react/pull/188

**Comment by nickhsine** [comment]
@garfieldduck  is going to implement BottomTags.
I am going to implement InfoBox.

**Comment by nickhsine** [comment]
Introduction is ongoing.

**Comment by nickhsine** [comment]
Leading Image is ongoing.

**Comment by hcchien** [comment]
![0412 - -02](https://cloud.githubusercontent.com/assets/101658/15529147/95981fc6-227d-11e6-812a-7c7c989d6cc8.png)

**Comment by hcchien** [comment]
![0425 -](https://cloud.githubusercontent.com/assets/101658/15529192/08e40184-227e-11e6-8b5e-90ae19e58fd5.png)

**Comment by hcchien** [comment]
![_ _ -](https://cloud.githubusercontent.com/assets/101658/15529296/ed382450-227e-11e6-837a-4392f5a14851.png)

**Comment by hcchien** [comment]
![_ _ -](https://cloud.githubusercontent.com/assets/101658/15529313/0974639a-227f-11e6-8f49-c949617f26f3.png)

**Comment by hcchien** [comment]
![_ _ -](https://cloud.githubusercontent.com/assets/101658/15531259/ffcf5e14-228b-11e6-93c3-c9981a6df47c.png)

**Comment by chiuyiying** [comment]
Hi all，我看了 mockup 之後，有一些疑問／意見如下：

1.
目前看到有兩種不同的設計，最後 final 版會是哪一種呢？以下我先依上傳順序，將[第一款](https://cloud.githubusercontent.com/assets/101658/15529192/08e40184-227e-11e6-8b5e-90ae19e58fd5.png)命名為Ａ款，[第二款](https://cloud.githubusercontent.com/assets/101658/15529296/ed382450-227e-11e6-837a-4392f5a14851.png)命名為Ｂ款。

2.
Ａ款的文章 header 會發生標題字數和作者字數產生衝突的排版問題。這個排版邏輯比較偏向平面設計，但不適合網頁版和 RWD。Ｂ款的排版方式會比較好。

3.
預設字體的選用應針對 Windows 和 OS 做不同設定。例如 Windows 可選擇微軟正黑體 (Microsoft JhengHei)，OS 可選擇蘋方 (PingFang TC)，英文語系的優先順序也可以做對應設定：Helvetica Neue、Lucida Grande 等等。另外，如果能夠解決效能問題，那 web font 會給 Windows 和 OS 讀者最一致的體驗。

4.
兩款設計的序言／引言設計都不甚理想；字體和內文並無明顯區隔，且顏色過淺，容易給人備註文字的聯想，建議可以參考 Quartz 的文章版面設計。序言 (preface) 和引言 (quote) 的設計應不相同，前者只會出現在文章最頂端、後者是不定時出現在文章中，讓讀者在閱讀中能有視覺喘息的空間。

5.
刊出日、作者資訊、文字大小、書籤、分享等附加資訊及功能，也建議可以參考 Quartz，做兩欄式設計，版面會更加活潑，讀者也不易讀到文末作者資訊就跳出，錯失閱讀其他文章的機會。

6.
Ａ款有許多元件設計光看 mockup 無法理解用途，可能需要後續說明。

7.
Ｂ款有一個 search bar，不太確定出現在那裡的用意是什麼。

8.
可多使用報導者的 CI 配色在版面設計中。
