### ISSUE TITLE
請問《少年報導者》有 RSS Feed 嗎？

### ISSUE THREAD

**Issue by typingmonk** [twreporter/twreporter-react#2267]
Hi twreporter:

想詢問是否有 https://kids.twreporter.org/ 的 rss feed 可以追蹤？
目前《少年報導者》footer 提供的 RSS 連結為：https://public.twreporter.org/rss/twreporter-rss.xml
應該還是只有提供主站《報導者》的新聞。

Related Issue: https://github.com/twreporter/twreporter-react/issues/59

**Comment by howar31** [comment]
Hello, 您要找的是不是這個呢？
[https://kids.twreporter.org/feed/](https://kids.twreporter.org/feed/)

**Comment by typingmonk** [comment]
Yes, 這是我要找的 RSS Feed.
謝謝您提供連結 :D
