### ISSUE TITLE
Dont show redux-logger on production

### ISSUE THREAD

**Issue by yhsiang** [twreporter/twreporter-react#257]
<img width="1280" alt="2016-07-30 10 49 05" src="https://cloud.githubusercontent.com/assets/93509/17267723/482ba3b2-5643-11e6-8b86-468be30e11e5.png">

剛剛稍微 review source，看起來是把 development 版本 deploy 上 production 了？

**Comment by nickhsine** [comment]
謝謝回報，改版會一起處理這個部分
