### ISSUE TITLE
apply eslint and editorconfig

### ISSUE THREAD

**Issue by kaddopur** [twreporter/twreporter-react#60]
@nickhsine 

Maybe we could start from presets like
- https://www.npmjs.com/package/eslint-config-airbnb
- https://www.npmjs.com/package/eslint-config-rackt

Editorconfig is a very useful tool to make the code style consistent
https://github.com/rackt/redux/blob/master/.editorconfig
```yml
# EditorConfig helps developers define and maintain
# consistent coding styles between different editors and IDEs.

root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2
```

**Comment by nickhsine** [comment]
@kaddopur :100:  :+1: 
thanks for your advice.
Becasue we are focusing bug fix now, will adopt eslint soon.

However, if you want to give us some PRs, we will totally be appreciated :)

**Comment by yutin1987** [comment]
++ :100:

**Comment by kaddopur** [comment]
I could do the PR and fix the styles :smile: 
But don't know the `indent` size for this project
Or let me just use `eslint-config-rackt` preset to start with?

**Comment by nickhsine** [comment]
Thanks Jason for helping!
We will try to fit the eslint after days.
