### ISSUE TITLE
node version?

### ISSUE THREAD

**Issue by yutin1987** [twreporter/twreporter-react#61]
希望能在 package.json 補上 node version的資訊.
Thanks.

https://docs.npmjs.com/files/package.json#engines

**Comment by jessy1092** [comment]
我用 v4.2.1 是沒問題

**Comment by nickhsine** [comment]
目前我們是用^4.0.0,
這方面的資訊會再補上去。
謝謝：）

**Comment by hcchien** [comment]
updated in package.json
