### ISSUE TITLE
upgrade react-flex-carousel to 1.0

### ISSUE THREAD

**Issue by kidwm** [twreporter/twreporter-react#644]
Sorry, here comes breaking change, because I didn't notice there is a typo `autoplayInteval` in previous versions.

I already fixed it in 1.0 release with correct name `autoPlayInterval`, along with some markup and styling change, take this commit as reference:
https://github.com/kidwm/react-flex-carousel/commit/9ba8ec1e95383e9d9ff8ade775422c7d3ef5d832

Please let me know if you have any problem after upgrade.

**Comment by nickhsine** [comment]
So far we won't upgrade the pkg version.

Thanks for information.
