### ISSUE TITLE
Maybe better box shadow

### ISSUE THREAD

**Issue by minipai** [twreporter/twreporter-react#76]
## before
<img width="927" alt="screen shot 2015-12-17 at 2 33 24 pm" src="https://cloud.githubusercontent.com/assets/239570/11862988/2fef72f8-a4cb-11e5-8688-a9008967b1db.png">

    box-shadow: rgba(0, 0, 0, 0.0901961) 0px 0px 15px;

## after
<img width="924" alt="screen shot 2015-12-17 at 2 33 38 pm" src="https://cloud.githubusercontent.com/assets/239570/11863015/67511a76-a4cb-11e5-8649-27e99794aae0.png">

    box-shadow: box-shadow: rgba(0, 0, 0, 0.0901961) 0px 30px 20px -20px, rgba(0, 0, 0, 0.0901961) 0px 0px 3px;

**Comment by hcchien** [comment]
謝謝，我們之後會改上   :)

**Comment by hcchien** [comment]
patched
