### ISSUE TITLE
npm start leads to 500 and readme instruction issue

### ISSUE THREAD

**Issue by muan** [twreporter/twreporter-react#77]
![image](https://cloud.githubusercontent.com/assets/1153134/11864105/511d1efa-a4dd-11e5-8462-620103195b52.png)

```
$ npm -v
2.14.7

$ node -v
v4.2.3

$ npm install
...

$ npm start

> twreporter-react@0.0.1 start /Users/muan/oss/twreporter-react
> webpack --progress && nodemon server

Hash: e548a46de06cae666cba  
Version: webpack 1.12.9
Time: 6269ms
   Asset     Size  Chunks             Chunk Names
 main.js  2.35 MB       0  [emitted]  main
main.css  20.7 kB       0  [emitted]  main
    + 611 hidden modules

WARNING in ./~/react-burger-menu/lib/menuFactory.js
Module not found: Error: Cannot resolve module 'imports' in /Users/muan/oss/twreporter-react/node_modules/react-burger-menu/lib
 @ ./~/react-burger-menu/lib/menuFactory.js 164:19-97
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server`
Server is listening to port: 3000
```

---

```
WARNING in ./~/react-burger-menu/lib/menuFactory.js
Module not found: Error: Cannot resolve module 'imports' in /Users/muan/oss/twreporter-react/node_modules/react-burger-menu/lib
 @ ./~/react-burger-menu/lib/menuFactory.js 164:19-97
```

:point_up: This is not related to the 500 and can be fixed by adding `imports-loader`, ref:  https://github.com/negomi/react-burger-menu/issues/13#issuecomment-145107302.

---

And I'm not sure how https://github.com/twreporter/twreporter-react/commit/549fe41af7b60c6f0801b1ee34a5b0e5679563d6#diff-04c6e90faac2675aa89e2176d2eec7d8R6 makes sense, doesn't that mean installing dev dependencies **only**? which I tried, but the dependencies couldn't resolve. cc @c9s

```
error peerinvalid The package karma-phantomjs-launcher@0.2.1 does not satisfy its siblings' peerDependencies requirements!
```

**Comment by kidwm** [comment]
@muan @c9s IIRC, there is only `npm install --production`

**Comment by muan** [comment]
@kidwm heh, https://github.com/npm/npm/issues/5554, it was supposed to go away but then didn't, https://github.com/npm/npm/issues/6200#issuecomment-130103681 :point_right: https://github.com/npm/npm/pull/9024#issuecomment-123516927. 

> I mean, you'd expect `npm install` wouldn't install dev dependencies, then run `npm install --dev`, then your cat dies and your house catches on fire. Not cool.

:joy::cat2::skull::house::fire::x::cool:

**Comment by kidwm** [comment]
@muan it should be `--only={prod[uction]|dev[elopment]` in this case after npm 3.3.0
@c9s just remove the `--dev`, that would be fine.

**Comment by muan** [comment]
To clarify, `localhost:3000` shows up as 500 after `npm install && npm start`, not`npm install --dev`.

**Comment by kidwm** [comment]
@muan I encountered this problem only once, did it always show up in your case?

**Comment by muan** [comment]
@kidwm yup, tried restarting and `rm -rf node_modules && npm install && npm start` as well, same result.

**Comment by kidwm** [comment]
@muan I can not to trigger this again.

**Comment by muan** [comment]
What's your node/NPM version? I am guessing that could be the reason, unless you tested with the versions I am using?

**Comment by kidwm** [comment]
@muan node 5.3.0 & npm 3.3.12

**Comment by nickhsine** [comment]
Would you like to try node ^4.0.0?

**Comment by kidwm** [comment]
@muan could you try the current HEAD after I introduce browserSync?

**Comment by nickhsine** [comment]
@muan have your tried current HEAD with node 5 and npm 3? 
My trying is ok now.

**Comment by muan** [comment]
> @muan could you try the current HEAD after I introduced browserSync?

hey it works! :sparkles: with node v4.2.3 & npm 2.14.7.

Thanks all.
