### ISSUE TITLE
twitter sharing with content not title

### ISSUE THREAD

**Issue by alphalin** [twreporter/twreporter-react#80]
For example,
This article
https://www.twreporter.org/a/hualien-wumingyi

When I click twitter share button, I see the text is article content but not title.
Like this:
http://twitter.com/share?url=https://www.twreporter.org/a/hualien-wumingyi&text=%E4%B8%83%E6%98%9F%E6%BD%AD%E7%95%B6%E7%84%B6%E6%98%AF%E6%95%B4%E5%80%8B%E8%8A%B1%E8%93%AE%E5%B1%85%E6%B0%91%E3%80%81%E5%8F%B0%E7%81%A3%E6%B0%91%E7%9C%BE%E7%9A%84%E9%87%8D%E8%A6%81%E5%85%AC%E5%85%B1%E8%B2%A1%EF%BC%8C%E5%AE%83%E4%B8%8D%E8%A9%B2%E8%A2%AB%E7%9F%AD%E6%9A%AB%E7%9A%84%E8%A7%80%E5%85%89%E5%88%A9%E7%9B%8A%E5%89%9D%E5%89%8A%E3%80%82...

I think using title as text is more reasonable.
Please consider to change it. Thanks.

**Comment by nickhsine** [comment]
fixed.
