### ISSUE TITLE
rss2.xml 格式不標準

### ISSUE THREAD

**Issue by gugod** [twreporter/twreporter-react#81]
我想將目前的 rss https://www.twreporter.org/a/rss2.xml 加入 http://gwene.org/ ，但因為格式不符標準而被拒絕：

用 W3C Validator 檢查之後也的確找出兩處錯誤。請參考 http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.twreporter.org%2Fa%2Frss2.xml

**Comment by hcchien** [comment]
tag @audreyt

**Comment by audreyt** [comment]
@hcchien Somehow https://www.twreporter.org/a/rss2.xml is 404 now but I've made the neccessary fix in https://github.com/twreporter/tr-projects-rest/pull/21 — the result can be validated in https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Faudreyt.github.io%2Finfographics%2Frss2.xml%3F

**Comment by nickhsine** [comment]
@audreyt 
thanks!
但由於我們現在後台有點問題，
所以暫時無法開放rss。
解決問題後會馬上開啟。

**Comment by hcchien** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.twreporter.org%2Fa%2Frss2.xml
