### ISSUE TITLE
rss2.xml 404 not found

### ISSUE THREAD

**Issue by imZack** [twreporter/twreporter-react#87]
- https://www.twreporter.org/a/rss2.xml

![image](https://cloud.githubusercontent.com/assets/690703/11911549/1ce55d64-a654-11e5-80bf-e1fd9d0b039e.png)

**Comment by hcchien** [comment]
Yes, it's known issue. We are working for that. thanks

**Comment by hcchien** [comment]
https://www.twreporter.org/a/rss2.xml, fixed. thanks
