### ISSUE TITLE
Consider adding a contributing guide

### ISSUE THREAD

**Issue by konekoya** [twreporter/twreporter-react#900]
Hi there,

Can you add a contribute guide for people who want to contribute to this repo?

Thanks :)

**Comment by nickhsine** [comment]
Sure, will add it later.

**Comment by YuCJ** [comment]
Thanks for the suggestion. 👍 We just added a contributing guide to the repo:
https://github.com/twreporter/twreporter-react/blob/master/CONTRIBUTING.md
We hope it will help developers to contribute to the project more easily.

**Comment by konekoya** [comment]
@YuCJ Thank you 👍
