### ISSUE TITLE
enable the category page

### ISSUE THREAD

**Issue by hcchien** [twreporter/twreporter-react#96]
![cat_mobile](https://cloud.githubusercontent.com/assets/101658/11935802/d3616c4e-a844-11e5-9dc6-89f1311e27c8.png)

**Comment by hcchien** [comment]
![cat](https://cloud.githubusercontent.com/assets/101658/11935835/0d964fce-a845-11e5-9d90-3cdec70300a8.png)

**Comment by kidwm** [comment]
Add `font-size: 27pt; font-weight: bold` in `.category-items` of `Tags.css`

**Comment by yutin1987** [comment]
:+1:
